#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then you should change the line above to use that shell, or set the
#       SHELL variable to that shell.
#   (2) Environments that can't unset variables, the following problem may
#       be encountered: "error: the impl.bat file could not be found".
#
#   Typical usage is: [ cmd ] ./gradlew [option] [task]
#   with: [-h|--help] to display this help message
#         [-v|--version] to display the Gradle version
#         [-q|--quiet] Quiet mode
#
##############################################################################

# Attempt to set APP_HOME
# Resolve links: $0 may be a softlink
app_path=$0
# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}; [ -n "$APP_HOME" ] &&
    APP_HOME=$(cd "$APP_HOME" 2>/dev/null && pwd) ||
    break
    app_path=$(ls -ld "$app_path")
do
    continue
done
APP_HOME=$(cd "${APP_HOME:-./}" 2>/dev/null && pwd) || exit 1
APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}
export APP_HOME
# Use default value of GRADLE_WRAPPER_PROPERTIES if not already set.
: ${GRADLE_WRAPPER_PROPERTIES:="$APP_HOME/gradle/wrapper/gradle-wrapper.properties"}
export GRADLE_WRAPPER_PROPERTIES
# Use default value of JAVA_HOME if not already set.
: ${JAVA_HOME:=}
if [ ! -z "$JAVA_HOME" ] ; then
    JAVA_HOME_ESCAPED="$(printf '%s\n' "$JAVA_HOME" | sed -e 's/[\/&]/\\&/g')"
    export JAVA_HOME_ESCAPED
fi
# Use default value of GRADLE_OPTS if not already set.
: ${GRADLE_OPTS:=}
export GRADLE_OPTS
# Determine the Java command to use to start the JVM.
if [ ! -z "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to \"$JAVA_HOME\" but java is not found in PATH: \"$JAVACMD\""
    fi
else
    JAVACMD="java"
    command -v java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
fi
# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $UNAME in
        Linux*)
            MAX_FD_LIMIT=$(ulimit -H -n)
            ulimit -n $MAX_FD_LIMIT
            ;;
    esac
fi
# For Darwin, add options to specify how the application appears in the dock
if $darwin; then
    GRADLE_OPTS="$GRADLE_OPTS \"-Xdock:name=$APP_NAME\" \"-Xdock:icon=$APP_HOME/media/gradle.icns\""
fi
# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CP=$( cygpath --path --mixed "$CP" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )
    JAVACMD=$( cygpath --unix "$JAVACMD" )
    for i in $(echo $CLASSPATH | tr ':' '\n' ) ; do
        j=$( cygpath --unix "$i" )
        CLASSPATH="$CLASSPATH$SEP$j"
    done
fi
# Provide a non-zero exit code without removing the PID.
# Use 1 as exit code.
die() {
    echo "$*"
    exit 1
}
# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $UNAME in
        Linux*)
            MAX_FD_LIMIT=$(ulimit -H -n)
            if [ $? -eq 0 ] ; then
                if [ "$MAX_FD_LIMIT" != "unlimited" ] ; then
                    ulimit -n $MAX_FD_LIMIT
                fi
            fi
            ;;
    esac
fi
# Escape application args
save() {
    for i; do printf '%s\n' "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/"; done
    echo " "
}
APP_ARGS=$(save "$@")
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar
exec "$JAVACMD" \
  $GRADLE_OPTS \
  -classpath "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain \
  "$APP_ARGS"
